using System.Text;
using LANCommander.Packaging.Changes;
using LANCommander.Packaging.Models;
using LANCommander.SDK.Enums;

namespace LANCommander.Packaging.LCX;

/// <summary>
/// Turns captured registry changes into install and uninstall PowerShell scripts.
/// </summary>
/// <remarks>
/// The Interposer reports which keys and values an installer wrote but not the data or type it
/// wrote, so the generated install script recreates the shape of the registry with empty
/// values. Capturing real values needs a change to the Interposer's hooks and wire format.
/// </remarks>
public static class ScriptGenerator
{
    public static List<GeneratedScript> Generate(PackageDefinition package)
    {
        var scripts = new List<GeneratedScript>();

        var hasRegistry = package.SelectedRegistryEntries.Count > 0;

        if (hasRegistry || package.PatchGameSpy)
            scripts.Add(GenerateInstallScript(package));

        if (hasRegistry)
            scripts.Add(GenerateUninstallScript(package));

        return scripts;
    }

    private static GeneratedScript GenerateInstallScript(PackageDefinition package)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Install Script - Generated by LANCommander Launcher");
        sb.AppendLine();

        var requiresAdmin = false;

        foreach (var group in GroupByKey(package.SelectedRegistryEntries))
        {
            var keyPath = ConvertToPowerShellRegistryPath(group.Key.KeyPath, group.Key.Architecture);

            if (IsMachineKey(group.Key.KeyPath))
                requiresAdmin = true;

            sb.AppendLine($"New-Item -Path \"{keyPath}\" -Force | Out-Null");

            foreach (var entry in group.Where(e => !string.IsNullOrEmpty(e.ValueName)))
                sb.AppendLine($"Set-ItemProperty -Path \"{keyPath}\" -Name \"{entry.ValueName}\" -Value \"\"");

            sb.AppendLine();
        }

        if (package.PatchGameSpy)
        {
            sb.AppendLine("# Patch GameSpy references for OpenSpy compatibility");
            sb.AppendLine("Edit-PatchGameSpy -Path $InstallDirectory");
            sb.AppendLine();
        }

        return new GeneratedScript
        {
            Type = ScriptType.Install,
            Contents = sb.ToString(),
            RequiresAdmin = requiresAdmin,
        };
    }

    private static GeneratedScript GenerateUninstallScript(PackageDefinition package)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Uninstall Script - Generated by LANCommander");
        sb.AppendLine();

        var requiresAdmin = false;

        foreach (var group in GroupByKey(package.SelectedRegistryEntries))
        {
            var keyPath = ConvertToPowerShellRegistryPath(group.Key.KeyPath, group.Key.Architecture);

            if (IsMachineKey(group.Key.KeyPath))
                requiresAdmin = true;

            foreach (var entry in group.Where(e => !string.IsNullOrEmpty(e.ValueName)))
                sb.AppendLine($"Remove-ItemProperty -Path \"{keyPath}\" -Name \"{entry.ValueName}\" -ErrorAction SilentlyContinue");

            sb.AppendLine($"Remove-Item -Path \"{keyPath}\" -ErrorAction SilentlyContinue");
            sb.AppendLine();
        }

        return new GeneratedScript
        {
            Type = ScriptType.Uninstall,
            Contents = sb.ToString(),
            RequiresAdmin = requiresAdmin,
        };
    }

    private static IEnumerable<IGrouping<(string KeyPath, ProcessArchitecture Architecture), RegistryChange>>
        GroupByKey(IEnumerable<RegistryChange> entries) =>
        entries.GroupBy(e => (e.KeyPath, e.SourceArchitecture));

    private static bool IsMachineKey(string keyPath) =>
        keyPath.StartsWith("HKLM", StringComparison.OrdinalIgnoreCase) ||
        keyPath.StartsWith("HKEY_LOCAL_MACHINE", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Rewrites a captured key path into a PowerShell provider path.
    /// </summary>
    /// <remarks>
    /// When the writing process was 32-bit, the write was subject to WOW64 redirection and
    /// physically landed under <c>WOW6432Node</c>. The hooks may report either form, so the
    /// redirected form is applied here. A script that writes to the 64-bit view instead would
    /// leave the game unable to find its own settings.
    /// </remarks>
    public static string ConvertToPowerShellRegistryPath(
        string keyPath,
        ProcessArchitecture sourceArchitecture = ProcessArchitecture.Unknown)
    {
        var converted = ConvertHive(keyPath);

        if (sourceArchitecture == ProcessArchitecture.X86)
            converted = ApplyWow64Redirection(converted);

        return converted;
    }

    private static string ConvertHive(string keyPath)
    {
        if (keyPath.StartsWith(@"HKEY_LOCAL_MACHINE\", StringComparison.OrdinalIgnoreCase))
            return @"HKLM:\" + keyPath[@"HKEY_LOCAL_MACHINE\".Length..];

        if (keyPath.StartsWith(@"HKEY_CURRENT_USER\", StringComparison.OrdinalIgnoreCase))
            return @"HKCU:\" + keyPath[@"HKEY_CURRENT_USER\".Length..];

        if (keyPath.StartsWith(@"HKEY_CLASSES_ROOT\", StringComparison.OrdinalIgnoreCase))
            return @"HKCR:\" + keyPath[@"HKEY_CLASSES_ROOT\".Length..];

        if (keyPath.StartsWith(@"HKEY_USERS\", StringComparison.OrdinalIgnoreCase))
            return @"HKU:\" + keyPath[@"HKEY_USERS\".Length..];

        if (keyPath.StartsWith(@"HKLM\", StringComparison.OrdinalIgnoreCase))
            return @"HKLM:\" + keyPath[@"HKLM\".Length..];

        if (keyPath.StartsWith(@"HKCU\", StringComparison.OrdinalIgnoreCase))
            return @"HKCU:\" + keyPath[@"HKCU\".Length..];

        return keyPath;
    }

    /// <summary>
    /// Inserts <c>WOW6432Node</c> after the <c>SOFTWARE</c> segment when it is not already
    /// present. Only <c>SOFTWARE</c> is redirected under WOW64.
    /// </summary>
    private static string ApplyWow64Redirection(string powerShellPath)
    {
        if (powerShellPath.Contains(@"WOW6432Node", StringComparison.OrdinalIgnoreCase))
            return powerShellPath;

        foreach (var hive in new[] { @"HKLM:\", @"HKCU:\", @"HKCR:\" })
        {
            if (!powerShellPath.StartsWith(hive, StringComparison.OrdinalIgnoreCase))
                continue;

            var remainder = powerShellPath[hive.Length..];

            if (!remainder.StartsWith("SOFTWARE", StringComparison.OrdinalIgnoreCase))
                return powerShellPath;

            var afterSoftware = remainder["SOFTWARE".Length..];
            
            if (afterSoftware.Length > 0 && afterSoftware[0] != '\\')
                return powerShellPath;

            return hive + @"SOFTWARE\WOW6432Node" + afterSoftware;
        }

        return powerShellPath;
    }
}
