#!/usr/bin/env python3
"""
Generate the Icon control's data from Phosphor Icons (https://phosphoricons.com, MIT License).

Outputs, next to this script:
    IconType.g.cs                     one enum member per icon, in PascalCase
    Resources/phosphor-<weight>.tsv.gz  "<IconType name>\t<inner SVG markup>" per line, per weight

The inner markup comes from the core repository's assets/ folder, where every weight is filled
geometry on a 256x256 view box drawn with currentColor, so it can be inlined into an <svg> as-is.

Usage:
    python generate-icons.py                  download phosphor-icons/core main
    python generate-icons.py --zip core.zip   use an already downloaded archive
"""

import argparse
import gzip
import io
import re
import sys
import zipfile
from pathlib import Path
from urllib.request import Request, urlopen

REPO_ZIP_URL = "https://github.com/phosphor-icons/core/archive/refs/heads/main.zip"
ASSETS_PREFIX = "core-main/assets/"

# Weights exposed by the Icon control (Regular is the default; the others are bool parameters)
WEIGHTS = ["regular", "bold", "fill", "duotone"]

HERE = Path(__file__).resolve().parent


def to_pascal_case(kebab: str) -> str:
    name = "".join(part.capitalize() for part in kebab.split("-"))
    # Enum members cannot start with a digit
    return f"_{name}" if name[0].isdigit() else name


def icon_name(filename: str, weight: str) -> str:
    stem = filename.removesuffix(".svg")
    return stem.removesuffix(f"-{weight}") if weight != "regular" else stem


_SVG_INNER = re.compile(r"<svg[^>]*>(.*)</svg>", re.DOTALL)


def inner_markup(svg: str) -> str:
    match = _SVG_INNER.search(svg)
    if not match:
        raise ValueError("not an svg document")
    return " ".join(match.group(1).split())


def load_zip(path: str | None) -> zipfile.ZipFile:
    if path:
        return zipfile.ZipFile(path)

    print(f"Downloading {REPO_ZIP_URL}")
    request = Request(REPO_ZIP_URL, headers={"User-Agent": "LANCommander-IconBuilder/1.0"})
    with urlopen(request, timeout=180) as response:
        return zipfile.ZipFile(io.BytesIO(response.read()))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--zip", help="Path to a downloaded phosphor-icons/core archive")
    args = parser.parse_args()

    archive = load_zip(args.zip)
    icons: dict[str, dict[str, str]] = {w: {} for w in WEIGHTS}

    for entry in archive.namelist():
        if not entry.startswith(ASSETS_PREFIX) or not entry.endswith(".svg"):
            continue

        weight, filename = entry[len(ASSETS_PREFIX):].split("/", 1)
        if weight not in icons:
            continue

        name = to_pascal_case(icon_name(filename, weight))
        icons[weight][name] = inner_markup(archive.read(entry).decode("utf-8"))

    names = sorted(icons["regular"])
    missing = [(w, n) for w in WEIGHTS for n in names if n not in icons[w]]
    if missing:
        print(f"Icons missing from some weights: {missing[:10]}", file=sys.stderr)
        sys.exit(1)

    resources = HERE / "Resources"
    resources.mkdir(exist_ok=True)

    for weight in WEIGHTS:
        lines = "".join(f"{name}\t{icons[weight][name]}\n" for name in names)
        # mtime=0 keeps the output byte-identical between runs
        with gzip.GzipFile(resources / f"phosphor-{weight}.tsv.gz", "wb", mtime=0) as out:
            out.write(lines.encode("utf-8"))

    members = "\n".join(f"    {name}," for name in names)
    (HERE / "IconType.g.cs").write_text(
        "// <auto-generated>\n"
        "// Generated by Controls/Icon/generate-icons.py from Phosphor Icons (MIT License). Do not edit.\n"
        "// </auto-generated>\n\n"
        "namespace LANCommander.Server.UI.Controls;\n\n"
        "/// <summary>Every Phosphor icon, for <see cref=\"Icon\"/>. Browse them at https://phosphoricons.com.</summary>\n"
        "public enum IconType\n{\n"
        "    None = 0,\n"
        f"{members}\n"
        "}\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"Wrote {len(names)} icons x {len(WEIGHTS)} weights")


if __name__ == "__main__":
    main()
