services:
  lancommander:
    image: lancommander/lancommander:latest
    container_name: lancommander
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Uncomment the line below to install SteamCMD
      # - STEAMCMD=1
      # Uncomment the line below to install WINE
      # - WINE=1
    volumes:
      - /path/to/appdata/config:/app/config
      - /path/to/appdata/Backups:/app/Backups
      - /path/to/appdata/Launcher:/app/Launcher
      - /path/to/appdata/Media:/app/Media
      - /path/to/appdata/Saves:/app/Saves
      - /path/to/appdata/Servers:/app/Servers
      - /path/to/appdata/Uploads:/app/Uploads
      - /path/to/appdata/Updates:/app/Updates
    ports:
      - 1337:1337/tcp   # Webinterface
      - 35891:35891/udp # Beacon Broadcast
      - 213:213/udp # IPX Relay
    restart: unless-stopped
