// Auto-generated by LANCommander.CompletionGenerator — do not edit manually

export interface CmdletParameter {
    name: string;
    type: string;
    mandatory: boolean;
    position: number | null;
    helpMessage: string | null;
    aliases: string[];
}

export interface CmdletDefinition {
    name: string;
    description: string | null;
    outputType: string | null;
    parameters: CmdletParameter[];
}

export const cmdlets: CmdletDefinition[] = [
    {
        name: "Connect-SteamCmd",
        description: null,
        outputType: "SteamCmdStatus",
        parameters: [
            {
                name: "Username",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam account username to log in with.",
                aliases: [],
            },
            {
                name: "Password",
                type: "SecureString",
                mandatory: false,
                position: null,
                helpMessage: "The password for the Steam account. If omitted, an anonymous login is attempted.",
                aliases: [],
            },
        ],
    },
    {
        name: "Convert-AspectRatio",
        description: null,
        outputType: "DisplayResolution",
        parameters: [
            {
                name: "Width",
                type: "int",
                mandatory: true,
                position: 0,
                helpMessage: "The base display width in pixels.",
                aliases: [],
            },
            {
                name: "Height",
                type: "int",
                mandatory: true,
                position: 1,
                helpMessage: "The base display height in pixels.",
                aliases: [],
            },
            {
                name: "AspectRatio",
                type: "double",
                mandatory: true,
                position: 2,
                helpMessage: "The target aspect ratio as a decimal (e.g. 1.7778 for 16:9).",
                aliases: [],
            },
        ],
    },
    {
        name: "ConvertFrom-SerializedBase64",
        description: null,
        outputType: "object",
        parameters: [
            {
                name: "Input",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "A Base64-encoded string containing YAML-serialized data to deserialize.",
                aliases: [],
            },
        ],
    },
    {
        name: "ConvertTo-SerializedBase64",
        description: null,
        outputType: "string",
        parameters: [
            {
                name: "Input",
                type: "object",
                mandatory: true,
                position: 0,
                helpMessage: "The object to serialize to YAML and encode as a Base64 string.",
                aliases: [],
            },
        ],
    },
    {
        name: "ConvertTo-StringBytes",
        description: null,
        outputType: "byte[]",
        parameters: [
            {
                name: "Input",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The string to convert to a byte array.",
                aliases: [],
            },
            {
                name: "BigEndian",
                type: "bool",
                mandatory: false,
                position: null,
                helpMessage: "Use big-endian byte order for UTF-16 encoding. Only applies when -Utf16 is set.",
                aliases: [],
            },
            {
                name: "MaxLength",
                type: "int",
                mandatory: false,
                position: null,
                helpMessage: "Maximum number of characters to include. The string will be truncated if longer. Set to 0 for no limit.",
                aliases: [],
            },
            {
                name: "MinLength",
                type: "int",
                mandatory: false,
                position: null,
                helpMessage: "Minimum number of characters in the output. The string will be right-padded with null characters if shorter. Set to 0 for no padding.",
                aliases: [],
            },
            {
                name: "Utf16",
                type: "bool",
                mandatory: false,
                position: null,
                helpMessage: "Encode as UTF-16 instead of ASCII. Use with -BigEndian for big-endian UTF-16.",
                aliases: [],
            },
        ],
    },
    {
        name: "Disconnect-SteamCmd",
        description: null,
        outputType: "SteamCmdStatus",
        parameters: [
            {
                name: "Username",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam account username to log out.",
                aliases: [],
            },
        ],
    },
    {
        name: "Edit-PatchBinary",
        description: null,
        outputType: null,
        parameters: [
            {
                name: "Offset",
                type: "long",
                mandatory: true,
                position: 0,
                helpMessage: "The byte offset within the file where the data should be written.",
                aliases: [],
            },
            {
                name: "Data",
                type: "byte[]",
                mandatory: true,
                position: 1,
                helpMessage: "The byte array to write at the specified offset.",
                aliases: [],
            },
            {
                name: "FilePath",
                type: "string",
                mandatory: true,
                position: 2,
                helpMessage: "The path to the binary file to patch.",
                aliases: ["f"],
            },
        ],
    },
    {
        name: "Edit-PatchGameSpy",
        description: null,
        outputType: null,
        parameters: [
            {
                name: "Path",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The root directory containing the game files to patch.",
                aliases: [],
            },
            {
                name: "Hostname",
                type: "string",
                mandatory: false,
                position: 1,
                helpMessage: "The replacement master server hostname. Must be exactly 12 characters. Defaults to \u0027openspy.net\u0027.",
                aliases: [],
            },
            {
                name: "PublicKey",
                type: "string",
                mandatory: false,
                position: 2,
                helpMessage: "The replacement public key for server authentication. Must match the original key length. Defaults to the OpenSpy public key.",
                aliases: [],
            },
            {
                name: "BinariesToPatch",
                type: "string[]",
                mandatory: false,
                position: 3,
                helpMessage: "Glob patterns for binary files to scan and patch. Defaults to \u0027*.dll\u0027, \u0027*.exe\u0027, \u0027*.ini\u0027.",
                aliases: [],
            },
            {
                name: "TextFilesToPatch",
                type: "string[]",
                mandatory: false,
                position: 4,
                helpMessage: "Glob patterns for text files to scan and patch (e.g. Unreal Engine INI configs). Defaults to \u0027*.ini\u0027.",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-GameManifest",
        description: null,
        outputType: "Game",
        parameters: [
            {
                name: "Path",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The directory path where the game manifest file is located.",
                aliases: [],
            },
            {
                name: "Id",
                type: "Guid",
                mandatory: true,
                position: null,
                helpMessage: "The unique identifier (GUID) of the game.",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-HorizontalFov",
        description: null,
        outputType: "int",
        parameters: [
            {
                name: "BaseFov",
                type: "int",
                mandatory: false,
                position: null,
                helpMessage: "The base horizontal field of view in degrees at 4:3 aspect ratio. Defaults to 90.",
                aliases: [],
            },
            {
                name: "Height",
                type: "int",
                mandatory: false,
                position: null,
                helpMessage: "The display height in pixels. Defaults to the primary display height.",
                aliases: [],
            },
            {
                name: "Width",
                type: "int",
                mandatory: false,
                position: null,
                helpMessage: "The display width in pixels. Defaults to the primary display width.",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-PrimaryDisplay",
        description: null,
        outputType: "Screen",
        parameters: [
        ],
    },
    {
        name: "Get-RedistributableOptions",
        description: null,
        outputType: "PSObject",
        parameters: [
            {
                name: "Path",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The install directory path where the game manifest is located.",
                aliases: [],
            },
            {
                name: "Id",
                type: "Guid",
                mandatory: true,
                position: null,
                helpMessage: "The unique identifier (GUID) of the game.",
                aliases: [],
            },
            {
                name: "Name",
                type: "string",
                mandatory: true,
                position: null,
                helpMessage: "The name of the redistributable to get options for.",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-SteamAppInfo",
        description: null,
        outputType: "AppInfo",
        parameters: [
            {
                name: "AppId",
                type: "uint",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam application ID to retrieve information for.",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-SteamCmdConnectionStatus",
        description: null,
        outputType: "SteamCmdConnectionStatus",
        parameters: [
            {
                name: "Username",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam account username to check the connection status for.",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-SteamCmdPath",
        description: null,
        outputType: "string",
        parameters: [
        ],
    },
    {
        name: "Get-SteamCmdProfile",
        description: null,
        outputType: "SteamCmdProfile",
        parameters: [
            {
                name: "Username",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam account username to retrieve the profile for.",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-SteamCmdProfiles",
        description: null,
        outputType: "SteamCmdProfile",
        parameters: [
        ],
    },
    {
        name: "Get-SteamWebAssetUri",
        description: null,
        outputType: "Uri",
        parameters: [
            {
                name: "AppId",
                type: "int",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam application ID.",
                aliases: [],
            },
            {
                name: "WebAssetType",
                type: "WebAssetType",
                mandatory: true,
                position: 1,
                helpMessage: "The type of web asset to retrieve the URI for (e.g. icon, header, capsule artwork).",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-UserCustomField",
        description: null,
        outputType: "string",
        parameters: [
            {
                name: "Name",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The name of the custom field to retrieve for the current user.",
                aliases: [],
            },
        ],
    },
    {
        name: "Get-VerticalFov",
        description: null,
        outputType: "int",
        parameters: [
            {
                name: "BaseFov",
                type: "int",
                mandatory: false,
                position: null,
                helpMessage: "The base vertical field of view in degrees at 4:3 aspect ratio. Defaults to 75.",
                aliases: [],
            },
            {
                name: "Height",
                type: "int",
                mandatory: false,
                position: null,
                helpMessage: "The display height in pixels. Defaults to the primary display height.",
                aliases: [],
            },
            {
                name: "Width",
                type: "int",
                mandatory: false,
                position: null,
                helpMessage: "The display width in pixels. Defaults to the primary display width.",
                aliases: [],
            },
        ],
    },
    {
        name: "Install-SteamContent",
        description: null,
        outputType: "SteamCmdInstallJob",
        parameters: [
            {
                name: "AppId",
                type: "uint",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam application ID to install.",
                aliases: [],
            },
            {
                name: "InstallDirectory",
                type: "string",
                mandatory: true,
                position: 1,
                helpMessage: "The directory path where the content should be installed.",
                aliases: [],
            },
            {
                name: "Username",
                type: "string",
                mandatory: false,
                position: null,
                helpMessage: "The Steam account username to use for downloading. If omitted, the default or anonymous account is used.",
                aliases: [],
            },
        ],
    },
    {
        name: "New-Package",
        description: null,
        outputType: "Package",
        parameters: [
            {
                name: "Path",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "Specifies the path to the directory containing the package contents to be archived.",
                aliases: ["p", "Directory"],
            },
            {
                name: "Version",
                type: "string",
                mandatory: true,
                position: 1,
                helpMessage: "Specifies the version number for this package.",
                aliases: ["v"],
            },
            {
                name: "Changelog",
                type: "string",
                mandatory: false,
                position: 2,
                helpMessage: "Specifies the changelog describing changes in this package version.",
                aliases: ["c", "Notes"],
            },
        ],
    },
    {
        name: "Out-PlayerAvatar",
        description: null,
        outputType: "string",
        parameters: [
        ],
    },
    {
        name: "Remove-SteamCmdProfile",
        description: null,
        outputType: null,
        parameters: [
            {
                name: "Username",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam account username whose profile should be deleted.",
                aliases: [],
            },
        ],
    },
    {
        name: "Remove-SteamContent",
        description: null,
        outputType: "SteamCmdStatus",
        parameters: [
            {
                name: "InstallDirectory",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The directory path of the installed Steam content to remove.",
                aliases: [],
            },
        ],
    },
    {
        name: "Search-SteamGames",
        description: null,
        outputType: "GameSearchResult",
        parameters: [
            {
                name: "Keyword",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The search term to look for in the Steam store.",
                aliases: [],
            },
        ],
    },
    {
        name: "Set-SteamCmdProfile",
        description: null,
        outputType: null,
        parameters: [
            {
                name: "Username",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The Steam account username for the profile.",
                aliases: [],
            },
            {
                name: "InstallDirectory",
                type: "string",
                mandatory: true,
                position: 1,
                helpMessage: "The default installation directory for this Steam profile.",
                aliases: [],
            },
        ],
    },
    {
        name: "Update-IniValue",
        description: null,
        outputType: "string",
        parameters: [
            {
                name: "Section",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "Specifies the section in the INI file that contains the key to be updated.",
                aliases: ["s"],
            },
            {
                name: "Key",
                type: "string",
                mandatory: true,
                position: 1,
                helpMessage: "Specifies the key within the section whose value should be updated.",
                aliases: ["k"],
            },
            {
                name: "Value",
                type: "string",
                mandatory: true,
                position: 2,
                helpMessage: "Specifies the new value to assign to the provided key.",
                aliases: ["v"],
            },
            {
                name: "FilePath",
                type: "string",
                mandatory: true,
                position: 3,
                helpMessage: "Specifies the file path to the INI file that should be processed.",
                aliases: ["f"],
            },
            {
                name: "AlwaysAppend",
                type: "SwitchParameter",
                mandatory: false,
                position: null,
                helpMessage: "If set, a new key-value pair will always be appended, even if the key already exists.",
                aliases: ["append"],
            },
            {
                name: "Clear",
                type: "SwitchParameter",
                mandatory: false,
                position: null,
                helpMessage: "If set, all instances of the specified key in the section will be cleared.",
                aliases: [],
            },
            {
                name: "Codepage",
                type: "string",
                mandatory: false,
                position: null,
                helpMessage: "Specifies the encoding (codepage) for reading and writing the INI file (e.g., \u0027UTF8\u0027, \u0027Latin\u0027, \u0027ASCII\u0027, \u0027Unicode\u0027).",
                aliases: ["encoding", "enc"],
            },
            {
                name: "InsertIndex",
                type: "int?",
                mandatory: false,
                position: null,
                helpMessage: "Specifies the index position at which the new key-value pair should be inserted. If not provided, the key is added at the end.",
                aliases: ["insert"],
            },
            {
                name: "KeepKeyDuplicates",
                type: "bool",
                mandatory: false,
                position: null,
                helpMessage: "If true, duplicate keys are allowed within the section.",
                aliases: ["keepkey", "keydup"],
            },
            {
                name: "KeepSectionDuplicates",
                type: "bool",
                mandatory: false,
                position: null,
                helpMessage: "If true, duplicate sections in the INI file are allowed.",
                aliases: ["keepsec", "secdup"],
            },
            {
                name: "NoAdd",
                type: "SwitchParameter",
                mandatory: false,
                position: null,
                helpMessage: "If set, restricts the operation to updating existing keys only; no new key will be added.",
                aliases: ["update-only", "only-update"],
            },
            {
                name: "NoKeyDuplicates",
                type: "SwitchParameter",
                mandatory: false,
                position: null,
                helpMessage: "If set, duplicate keys in the section are prevented.",
                aliases: ["nokey", "nokeydup"],
            },
            {
                name: "NoSectionDuplicates",
                type: "SwitchParameter",
                mandatory: false,
                position: null,
                helpMessage: "If set, duplicate section names are not permitted in the INI file.",
                aliases: ["nosec", "nosecdup"],
            },
            {
                name: "OnlyRemove",
                type: "SwitchParameter",
                mandatory: false,
                position: null,
                helpMessage: "If set, the key(s) will only be removed from the section without updating or adding any value.",
                aliases: ["remove-only"],
            },
            {
                name: "UpdateOrAdd",
                type: "SwitchParameter",
                mandatory: false,
                position: null,
                helpMessage: "If set, the cmdlet will update an existing key or add a new one if it does not exist.",
                aliases: ["add"],
            },
            {
                name: "WrapValueInQuotes",
                type: "bool?",
                mandatory: false,
                position: null,
                helpMessage: "If set, controls whether the value will be wrapped in quotes. Nullable: if null, adds quotes if missing; if true, enforces quotes; if false, removes quotes.",
                aliases: ["wrap", "quotes"],
            },
        ],
    },
    {
        name: "Update-UserCustomField",
        description: null,
        outputType: "string",
        parameters: [
            {
                name: "Name",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The name of the custom field to update.",
                aliases: [],
            },
            {
                name: "Value",
                type: "string",
                mandatory: true,
                position: 1,
                helpMessage: "The new value to set for the custom field.",
                aliases: [],
            },
        ],
    },
    {
        name: "Write-GameManifest",
        description: null,
        outputType: "string",
        parameters: [
            {
                name: "Path",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The directory path where the game manifest file should be written.",
                aliases: [],
            },
            {
                name: "Manifest",
                type: "Game",
                mandatory: true,
                position: 1,
                helpMessage: "The game manifest object to serialize and write to disk.",
                aliases: [],
            },
        ],
    },
    {
        name: "Write-ReplaceContentInFile",
        description: null,
        outputType: "string",
        parameters: [
            {
                name: "Pattern",
                type: "string",
                mandatory: true,
                position: 0,
                helpMessage: "The regular expression pattern to search for in the file content.",
                aliases: [],
            },
            {
                name: "Substitution",
                type: "string",
                mandatory: true,
                position: 1,
                helpMessage: "The replacement string. Supports regex substitution groups ($1, $2, etc.).",
                aliases: [],
            },
            {
                name: "FilePath",
                type: "string",
                mandatory: true,
                position: 2,
                helpMessage: "The path to the text file to modify.",
                aliases: ["f"],
            },
        ],
    },
];

export const builtinCmdlets: CmdletDefinition[] = [
];

export interface TypeProperty {
    name: string;
    type: string;
}

export interface TypeDefinition {
    name: string;
    properties: TypeProperty[];
}

export const variableTypes: TypeDefinition[] = [
    {
        name: "Game",
        properties: [
            {
                name: "Actions",
                type: "Action[]",
            },
            {
                name: "Archives",
                type: "Archive[]",
            },
            {
                name: "BaseGameId",
                type: "Guid",
            },
            {
                name: "Collections",
                type: "Collection[]",
            },
            {
                name: "CreatedOn",
                type: "DateTime",
            },
            {
                name: "CustomFields",
                type: "GameCustomField[]",
            },
            {
                name: "DependentGames",
                type: "Guid[]",
            },
            {
                name: "Description",
                type: "string",
            },
            {
                name: "Developers",
                type: "Company[]",
            },
            {
                name: "DirectoryName",
                type: "string",
            },
            {
                name: "Engine",
                type: "Engine",
            },
            {
                name: "ExternalIds",
                type: "GameExternalId[]",
            },
            {
                name: "Genres",
                type: "Genre[]",
            },
            {
                name: "Id",
                type: "Guid",
            },
            {
                name: "InLibrary",
                type: "bool",
            },
            {
                name: "InstallDirectory",
                type: "string",
            },
            {
                name: "IsAddon",
                type: "bool",
            },
            {
                name: "Keys",
                type: "Key[]",
            },
            {
                name: "Media",
                type: "Media[]",
            },
            {
                name: "MultiplayerModes",
                type: "MultiplayerMode[]",
            },
            {
                name: "Notes",
                type: "string",
            },
            {
                name: "Platforms",
                type: "Platform[]",
            },
            {
                name: "PlaySessions",
                type: "PlaySession[]",
            },
            {
                name: "Publishers",
                type: "Company[]",
            },
            {
                name: "Redistributables",
                type: "Redistributable[]",
            },
            {
                name: "ReleasedOn",
                type: "DateTime",
            },
            {
                name: "SavePaths",
                type: "SavePath[]",
            },
            {
                name: "Saves",
                type: "Save[]",
            },
            {
                name: "Scripts",
                type: "Script[]",
            },
            {
                name: "Servers",
                type: "Server[]",
            },
            {
                name: "Singleplayer",
                type: "bool",
            },
            {
                name: "SortTitle",
                type: "string",
            },
            {
                name: "Tags",
                type: "Tag[]",
            },
            {
                name: "Title",
                type: "string",
            },
            {
                name: "Tools",
                type: "Tool[]",
            },
            {
                name: "Type",
                type: "GameType",
            },
            {
                name: "UpdatedOn",
                type: "DateTime",
            },
        ],
    },
    {
        name: "GameManifest",
        properties: [
            {
                name: "Actions",
                type: "Action[]",
            },
            {
                name: "Addons",
                type: "Game[]",
            },
            {
                name: "Archives",
                type: "Archive[]",
            },
            {
                name: "BaseGame",
                type: "string",
            },
            {
                name: "BaseGameId",
                type: "Guid",
            },
            {
                name: "Collections",
                type: "Collection[]",
            },
            {
                name: "CreatedBy",
                type: "string",
            },
            {
                name: "CreatedOn",
                type: "DateTime",
            },
            {
                name: "CustomFields",
                type: "GameCustomField[]",
            },
            {
                name: "Description",
                type: "string",
            },
            {
                name: "Developers",
                type: "Company[]",
            },
            {
                name: "DirectoryName",
                type: "string",
            },
            {
                name: "Engine",
                type: "Engine",
            },
            {
                name: "ExternalIds",
                type: "GameExternalId[]",
            },
            {
                name: "Genres",
                type: "Genre[]",
            },
            {
                name: "Id",
                type: "Guid",
            },
            {
                name: "InstallDirectory",
                type: "string",
            },
            {
                name: "IsAddon",
                type: "bool",
            },
            {
                name: "Keys",
                type: "Key[]",
            },
            {
                name: "ManifestVersion",
                type: "string",
            },
            {
                name: "Media",
                type: "Media[]",
            },
            {
                name: "MultiplayerModes",
                type: "MultiplayerMode[]",
            },
            {
                name: "Notes",
                type: "string",
            },
            {
                name: "Platforms",
                type: "Platform[]",
            },
            {
                name: "PlaySessions",
                type: "PlaySession[]",
            },
            {
                name: "Publishers",
                type: "Company[]",
            },
            {
                name: "Redistributables",
                type: "Redistributable[]",
            },
            {
                name: "ReleasedOn",
                type: "DateTime",
            },
            {
                name: "SavePaths",
                type: "SavePath[]",
            },
            {
                name: "Saves",
                type: "Save[]",
            },
            {
                name: "Scripts",
                type: "Script[]",
            },
            {
                name: "Singleplayer",
                type: "bool",
            },
            {
                name: "SortTitle",
                type: "string",
            },
            {
                name: "Tags",
                type: "Tag[]",
            },
            {
                name: "Title",
                type: "string",
            },
            {
                name: "Tools",
                type: "Tool[]",
            },
            {
                name: "Type",
                type: "GameType",
            },
            {
                name: "UpdatedBy",
                type: "string",
            },
            {
                name: "UpdatedOn",
                type: "DateTime",
            },
            {
                name: "Version",
                type: "string",
            },
        ],
    },
    {
        name: "Redistributable",
        properties: [
            {
                name: "Archives",
                type: "Archive[]",
            },
            {
                name: "CreatedOn",
                type: "DateTime",
            },
            {
                name: "Description",
                type: "string",
            },
            {
                name: "Id",
                type: "Guid",
            },
            {
                name: "Name",
                type: "string",
            },
            {
                name: "Notes",
                type: "string",
            },
            {
                name: "OptionSchema",
                type: "string",
            },
            {
                name: "ReleasedOn",
                type: "DateTime",
            },
            {
                name: "Scripts",
                type: "Script[]",
            },
            {
                name: "UpdatedOn",
                type: "DateTime",
            },
        ],
    },
    {
        name: "RedistributableManifest",
        properties: [
            {
                name: "Archives",
                type: "Archive[]",
            },
            {
                name: "CreatedBy",
                type: "string",
            },
            {
                name: "CreatedOn",
                type: "DateTime",
            },
            {
                name: "Description",
                type: "string",
            },
            {
                name: "Id",
                type: "Guid",
            },
            {
                name: "ManifestVersion",
                type: "string",
            },
            {
                name: "Name",
                type: "string",
            },
            {
                name: "Notes",
                type: "string",
            },
            {
                name: "Options",
                type: "KeyValuePair\u00602[]",
            },
            {
                name: "OptionSchema",
                type: "string",
            },
            {
                name: "ReleasedOn",
                type: "DateTime",
            },
            {
                name: "Scripts",
                type: "Script[]",
            },
            {
                name: "UpdatedBy",
                type: "string",
            },
            {
                name: "UpdatedOn",
                type: "DateTime",
            },
        ],
    },
    {
        name: "Server",
        properties: [
            {
                name: "Actions",
                type: "Action[]",
            },
            {
                name: "Arguments",
                type: "string",
            },
            {
                name: "Autostart",
                type: "bool",
            },
            {
                name: "AutostartDelay",
                type: "int",
            },
            {
                name: "AutostartMethod",
                type: "ServerAutostartMethod",
            },
            {
                name: "CreatedOn",
                type: "DateTime",
            },
            {
                name: "Game",
                type: "Game",
            },
            {
                name: "Host",
                type: "string",
            },
            {
                name: "HttpPaths",
                type: "ServerHttpPath[]",
            },
            {
                name: "Id",
                type: "Guid",
            },
            {
                name: "Name",
                type: "string",
            },
            {
                name: "OnStartScriptPath",
                type: "string",
            },
            {
                name: "OnStopScriptPath",
                type: "string",
            },
            {
                name: "Path",
                type: "string",
            },
            {
                name: "Port",
                type: "int",
            },
            {
                name: "ProcessTerminationMethod",
                type: "ProcessTerminationMethod",
            },
            {
                name: "Scripts",
                type: "Script[]",
            },
            {
                name: "ServerConsoles",
                type: "ServerConsole[]",
            },
            {
                name: "UpdatedOn",
                type: "DateTime",
            },
            {
                name: "UseShellExecute",
                type: "bool",
            },
            {
                name: "WorkingDirectory",
                type: "string",
            },
        ],
    },
    {
        name: "Tool",
        properties: [
            {
                name: "Archives",
                type: "Archive[]",
            },
            {
                name: "CreatedOn",
                type: "DateTime",
            },
            {
                name: "Description",
                type: "string",
            },
            {
                name: "Id",
                type: "Guid",
            },
            {
                name: "Name",
                type: "string",
            },
            {
                name: "Notes",
                type: "string",
            },
            {
                name: "ReleasedOn",
                type: "DateTime",
            },
            {
                name: "Scripts",
                type: "Script[]",
            },
            {
                name: "UpdatedOn",
                type: "DateTime",
            },
        ],
    },
    {
        name: "ToolManifest",
        properties: [
            {
                name: "Actions",
                type: "Action[]",
            },
            {
                name: "Archives",
                type: "Archive[]",
            },
            {
                name: "CreatedBy",
                type: "string",
            },
            {
                name: "CreatedOn",
                type: "DateTime",
            },
            {
                name: "Description",
                type: "string",
            },
            {
                name: "Games",
                type: "Game[]",
            },
            {
                name: "Id",
                type: "Guid",
            },
            {
                name: "ManifestVersion",
                type: "string",
            },
            {
                name: "Name",
                type: "string",
            },
            {
                name: "Notes",
                type: "string",
            },
            {
                name: "ReleasedOn",
                type: "DateTime",
            },
            {
                name: "Scripts",
                type: "Script[]",
            },
            {
                name: "UpdatedBy",
                type: "string",
            },
            {
                name: "UpdatedOn",
                type: "DateTime",
            },
        ],
    },
    {
        name: "User",
        properties: [
            {
                name: "Alias",
                type: "string",
            },
            {
                name: "Id",
                type: "Guid",
            },
            {
                name: "Name",
                type: "string",
            },
            {
                name: "UserName",
                type: "string",
            },
        ],
    },
];

export const scriptTypeValues: string[] = [
    "Install",
    "Uninstall",
    "NameChange",
    "KeyChange",
    "SaveUpload",
    "SaveDownload",
    "DetectInstall",
    "BeforeStart",
    "AfterStop",
    "GameStarted",
    "GameStopped",
    "UserRegistration",
    "UserLogin",
    "ApplicationStart",
    "Package",
    "RunWrapper",
];
