using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Text.Json.Nodes;

namespace LANCommander.SchemaGenerator;

/// <summary>
/// Reflects over the LANCommander.SDK manifest models (<see cref="SDK.Models.Manifest"/>) and produces
/// a JSON Schema (2020-12) describing the YAML manifest that is embedded as <c>Manifest.yml</c>
/// in an exported/packaged LCX file.
///
/// Only types reachable from the requested root type are emitted, so each root schema file is fully
/// self-contained (no cross-file <c>$ref</c>s to resolve) even though the manifest object graph is
/// mutually recursive (e.g. Game &lt;-&gt; Tool, Game -&gt; Game via Addons).
/// </summary>
public sealed class ManifestSchemaBuilder
{
    private const string ManifestNamespacePrefix = "LANCommander";

    private readonly Dictionary<string, JsonObject> _defs = new();
    private readonly HashSet<string> _building = new();

    public static JsonObject BuildRootSchema(Type rootType, string version, string baseUrl)
        => new ManifestSchemaBuilder().Build(rootType, version, baseUrl);

    private JsonObject Build(Type rootType, string version, string baseUrl)
    {
        var rootDefName = GetOrBuildDef(rootType);

        var schema = new JsonObject
        {
            ["$schema"] = "https://json-schema.org/draft/2020-12/schema",
            ["$id"] = $"{baseUrl.TrimEnd('/')}/{version}/{rootType.Name}.schema.json",
            ["$comment"] = "Auto-generated by LANCommander.SchemaGenerator from LANCommander.SDK.Models.Manifest — do not edit manually.",
            ["title"] = $"LANCommander {rootType.Name} Manifest",
            ["description"] = $"Schema for the Manifest.yml file describing a LANCommander {rootType.Name} package (LCX), generated for LANCommander {version}.",
        };

        // Clone (rather than move) the root type's own definition onto the top level so both the
        // top-level document and any recursive/cross-referencing `$ref`s (e.g. Game.Addons: Game[],
        // Tool.Games: Game[]) resolve correctly.
        var rootDef = _defs[rootDefName];
        foreach (var (key, value) in rootDef)
            schema[key] = value?.DeepClone();

        if (_defs.Count > 0)
        {
            var defsNode = new JsonObject();

            foreach (var (name, def) in _defs.OrderBy(d => d.Key, StringComparer.Ordinal))
                defsNode[name] = def;

            schema["$defs"] = defsNode;
        }

        return schema;
    }

    private string GetOrBuildDef(Type type)
    {
        var name = type.Name;

        if (_defs.ContainsKey(name) || _building.Contains(name))
            return name;

        // Reserve the name before walking properties so self/mutually-recursive references
        // (Game -> Tool -> Game, Game -> Addons -> Game) short-circuit back to a `$ref` instead
        // of recursing forever.
        _building.Add(name);

        var properties = new JsonObject();

        foreach (var property in GetSerializableProperties(type))
            properties[property.Name] = BuildPropertySchema(property);

        var def = new JsonObject
        {
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["properties"] = properties,
        };

        _building.Remove(name);
        _defs[name] = def;

        return name;
    }

    private static IEnumerable<PropertyInfo> GetSerializableProperties(Type type) =>
        type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanRead && p.CanWrite)
            .Where(p => p.GetCustomAttributes().All(a => a.GetType().Name != "YamlIgnoreAttribute"))
            .OrderBy(p => p.Name, StringComparer.Ordinal);

    private JsonNode BuildPropertySchema(PropertyInfo property)
    {
        var schema = BuildTypeSchema(property.PropertyType);

        var maxLength = property.GetCustomAttribute<MaxLengthAttribute>()?.Length
            ?? property.GetCustomAttribute<StringLengthAttribute>()?.MaximumLength;

        if (maxLength is > 0 && schema is JsonObject obj && IsStringType(obj))
            obj["maxLength"] = maxLength.Value;

        return schema;
    }

    private static bool IsStringType(JsonObject obj)
    {
        var type = obj["type"];

        if (type is JsonValue value && value.TryGetValue(out string? s))
            return s == "string";

        if (type is JsonArray array)
            return array.Any(n => n is JsonValue v && v.TryGetValue(out string? s2) && s2 == "string");

        return false;
    }

    private JsonNode BuildTypeSchema(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        var nullable = underlying != null;
        var effective = underlying ?? type;

        if (effective == typeof(string))
            return new JsonObject { ["type"] = "string" };

        if (effective == typeof(bool))
            return NullableScalar("boolean", nullable);

        if (effective == typeof(int) || effective == typeof(long) || effective == typeof(uint) ||
            effective == typeof(short) || effective == typeof(byte))
            return NullableScalar("integer", nullable);

        if (effective == typeof(double) || effective == typeof(float) || effective == typeof(decimal))
            return NullableScalar("number", nullable);

        if (effective == typeof(Guid))
        {
            var obj = NullableScalar("string", nullable);
            obj["format"] = "uuid";
            return obj;
        }

        if (effective == typeof(DateTime) || effective == typeof(DateTimeOffset))
        {
            var obj = NullableScalar("string", nullable);
            obj["format"] = "date-time";
            return obj;
        }

        if (effective.IsEnum)
            return BuildEnumSchema(effective, nullable);

        if (TryGetDictionaryValueType(effective, out var dictionaryValueType))
        {
            return new JsonObject
            {
                ["type"] = "object",
                ["additionalProperties"] = BuildTypeSchema(dictionaryValueType!),
            };
        }

        var elementType = GetEnumerableElementType(effective);
        if (elementType != null)
        {
            return new JsonObject
            {
                ["type"] = "array",
                ["items"] = BuildTypeSchema(elementType),
            };
        }

        if (effective.IsClass && effective.Namespace?.StartsWith(ManifestNamespacePrefix, StringComparison.Ordinal) == true)
        {
            var name = GetOrBuildDef(effective);
            return new JsonObject { ["$ref"] = $"#/$defs/{name}" };
        }

        // Fallback for anything unanticipated — keep the manifest generator resilient to future
        // SDK model changes rather than throwing.
        return new JsonObject();
    }

    private static JsonObject NullableScalar(string typeName, bool nullable) =>
        new() { ["type"] = nullable ? new JsonArray(typeName, "null") : typeName };

    private static JsonNode BuildEnumSchema(Type enumType, bool nullable)
    {
        var names = Enum.GetNames(enumType);

        if (enumType.GetCustomAttribute<FlagsAttribute>() != null)
        {
            var alternation = string.Join("|", names);

            return new JsonObject
            {
                ["type"] = nullable ? new JsonArray("string", "null") : "string",
                ["description"] = $"Comma-separated combination of one or more flags: {string.Join(", ", names)}. Use \"None\" (or omit the field) for no flags.",
                ["pattern"] = $"^({alternation})(\\s*,\\s*({alternation}))*$",
            };
        }

        var descriptions = names.Select(n =>
        {
            var display = enumType.GetMember(n)[0].GetCustomAttribute<DisplayAttribute>()?.Name;
            return display != null ? $"{n} ({display})" : n;
        });

        var enumValues = new JsonArray();
        foreach (var n in names)
            enumValues.Add(n);
        if (nullable)
            enumValues.Add(null);

        return new JsonObject
        {
            ["type"] = nullable ? new JsonArray("string", "null") : "string",
            ["enum"] = enumValues,
            ["description"] = $"One of: {string.Join(", ", descriptions)}.",
        };
    }

    private static bool TryGetDictionaryValueType(Type type, out Type? valueType)
    {
        var dictionaryInterface = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Dictionary<,>)
            ? type
            : type.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IDictionary<,>));

        if (dictionaryInterface == null)
        {
            valueType = null;
            return false;
        }

        valueType = dictionaryInterface.GetGenericArguments()[1];
        return true;
    }

    private static Type? GetEnumerableElementType(Type type)
    {
        if (type == typeof(string))
            return null;

        if (type.IsArray)
            return type.GetElementType();

        if (type.IsGenericType)
        {
            var def = type.GetGenericTypeDefinition();
            if (def == typeof(ICollection<>) || def == typeof(IEnumerable<>) ||
                def == typeof(List<>) || def == typeof(IList<>))
                return type.GetGenericArguments()[0];
        }

        var enumerableInterface = type.GetInterfaces()
            .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));

        return enumerableInterface?.GetGenericArguments()[0];
    }
}
