// fs_dos.cpp — the fs.h seam on DOS.
//
// DJGPP layers a POSIX-shaped libc over INT 21h, so stat/mkdir/remove are all
// available and mean what they mean everywhere else. The DOS-specific part is
// naming: without a long filename driver loaded the filesystem is 8.3, so the
// temp name is built to fit in eight characters and generated by hand rather
// than through tmpnam(), which returns a name in the *current* directory.

#include "app/fs.h"

#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace launcher
{

    bool fs_mkdir(const std::string &path)
    {
        if (path.empty())
            return false;

        if (::mkdir(path.c_str(), 0777) == 0)
            return true;

        // Already there is success as far as the seam is concerned.
        struct stat st;
        return ::stat(path.c_str(), &st) == 0 && S_ISDIR(st.st_mode);
    }

    long long fs_file_size(const std::string &path)
    {
        if (path.empty())
            return -1;

        struct stat st;
        if (::stat(path.c_str(), &st) != 0)
            return -1;
        if (S_ISDIR(st.st_mode))
            return -1;

        return (long long)st.st_size;
    }

    bool fs_remove(const std::string &path)
    {
        return !path.empty() && std::remove(path.c_str()) == 0;
    }

    bool fs_rename(const std::string &from, const std::string &to)
    {
        if (from.empty() || to.empty())
            return false;

        // DOS rename() fails outright if the destination exists.
        std::remove(to.c_str());
        return std::rename(from.c_str(), to.c_str()) == 0;
    }

    bool fs_rmdir(const std::string &path)
    {
        return !path.empty() && ::rmdir(path.c_str()) == 0;
    }

    std::string fs_temp_file(const char *prefix)
    {
        // TEMP, then TMP, then the current directory. Neither variable is
        // guaranteed on DOS, and a machine that has neither is common enough
        // that failing would be the wrong answer.
        const char *dir = std::getenv("TEMP");
        if (!dir || !*dir)
            dir = std::getenv("TMP");
        if (!dir || !*dir)
            dir = ".";

        std::string base(dir);
        const char last = base[base.size() - 1];
        if (last != '\\' && last != '/')
            base += '\\';

        char stem[4] = "lcl";
        if (prefix && *prefix)
        {
            std::strncpy(stem, prefix, 3);
            stem[3] = '\0';
        }

        // "lcl" + five digits fills the 8.3 name exactly. Wrapping at 100000
        // rather than giving up keeps a machine that somehow accumulated a
        // full set of stale temp files working.
        for (unsigned int i = 0; i < 100000u; ++i)
        {
            char name[32];
            std::sprintf(name, "%s%05u.tmp", stem, i);

            const std::string candidate = base + name;
            if (fs_file_size(candidate) < 0)
            {
                // Created here, matching GetTempFileNameA: the caller is
                // handed a name that is already taken, so a second call
                // cannot return the same one.
                std::FILE *f = std::fopen(candidate.c_str(), "wb");
                if (!f)
                    continue;
                std::fclose(f);
                return candidate;
            }
        }

        return std::string();
    }

} // namespace launcher
