#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders for LANCommander
mkdir -p \
    /config/{Uploads,Updates,Saves,Media,Launcher,Logs,Backups}

# files needed by LANCommander
if [[ ! -f /config/Settings.yml ]]; then
    touch /config/Settings.yml
fi

# permissions
lsiown -R abc:abc \
     /config
lsiown -R abc:abc \
     /app/LANCommander
