#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders for LANCommander
mkdir -p \
    /config/{Uploads,Updates,Saves,Media,Launcher,Logs,Backups}

# files needed by LANCommander
if [[ ! -f /config/Settings.yml ]]; then
    cp /defaults/Settings.yml /config/Settings.yml
fi
if [[ ! -f /config/LANCommander.db ]]; then
    sqlite3 /config/LANCommander.db "VACUUM;"
fi
if [[ ! -f /config/internal.log ]]; then
    touch /config/internal.log
fi

# permissions
lsiown -R abc:abc \
     /config
lsiown -R abc:abc \
     /app/LANCommander
