#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders for LANCommander
mkdir -p \
    /config/LANCommander/{Uploads,Updates,Saves,Media,Logs,Backups,Icon}

# files needed by LANCommander
if [[ ! -f /config/LANCommander/Settings.yml ]]; then
    cp /defaults/Settings.yml /config/LANCommander/Settings.yml
fi
if [[ ! -f /config/LANCommander/LANCommander.db ]]; then
    sqlite3 /config/LANCommander/LANCommander.db "VACUUM;"
    #touch /config/LANCommander/LANCommander.db
fi
if [[ ! -f /config/LANCommander/internal.log ]]; then
    touch /config/LANCommander/internal.log
fi

# permissions
lsiown -R abc:abc \
     /config
