#!/usr/bin/with-contenv bash
# shellcheck shell=bash

lsiown -R abc:abc \
     /app/LANCommander

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
        cd /app/LANCommander s6-setuidgid abc /app/LANCommander/LANCommander.Server
