name: LANCommander Nightly

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 3AM CST
    # CST is UTC-6, so midnight CST = 09:00 UTC
    - cron: '0 9 * * *'
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lancommander/lancommander

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  # --------------------------------------------------------------------------
  # 1) PREP JOB: figure out the latest semver, build nightly version,
  #    check if there are commits since the last nightly tag. If none,
  #    skip the rest of the workflow.
  # --------------------------------------------------------------------------
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.102

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20'

      - name: Run Build Script
        shell: pwsh
        run: |
          ./LANCommander.Build/Nightly.ps1
        

  # --------------------------------------------------------------------------
  # 2) BUILD JOBS (Server/Launcher) - only run if changes == 'true'
  #    Each calls your local workflow YAML with correct indentation
  # --------------------------------------------------------------------------

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        platform: [win, linux, osx]
        architecture: [x64, arm64]
        include:
          - platform: win
            name: Windows
          - platform: linux
            name: Linux
          - platform: osx
            name: macOS
    needs: [prep]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: build-server
        uses: ./.github/actions/LANCommander.Server
        with:
          build_dotnet_version: ${{ needs.prep.outputs.build_dotnet_version }}
          version_semver: ${{ needs.prep.outputs.version_semver }}
          version_tag: ${{ needs.prep.outputs.version_tag }}
          build_runtime: ${{ matrix.platform }}-${{ matrix.architecture }}
          build_arch: ${{ matrix.architecture }}
          build_platform: ${{ matrix.name }}
          build_configuration: Debug
      - name: Upload Server Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build-server.outputs.artifact }}
          name: LANCommander.Server-${{ matrix.name }}-${{ matrix.architecture }}-v${{ needs.prep.outputs.version_tag }}.zip
      - id: build-launcher
        uses: ./.github/actions/LANCommander.Launcher
        with:
          build_dotnet_version: ${{ needs.prep.outputs.build_dotnet_version }}
          version_semver: ${{ needs.prep.outputs.version_semver }}
          version_tag: ${{ needs.prep.outputs.version_tag }}
          build_runtime: ${{ matrix.platform }}-${{ matrix.architecture }}
          build_arch: ${{ matrix.architecture }}
          build_platform: ${{ matrix.name }}
          build_configuration: Debug
      - name: Upload Launcher Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build-launcher.outputs.artifact }}
          name: LANCommander.Launcher-${{ matrix.name }}-${{ matrix.architecture }}-v${{ needs.prep.outputs.version_tag }}.zip

  # --------------------------------------------------------------------------
  # 3) FINALIZE: if changes == 'true', gather artifacts + push Docker:nightly
  # --------------------------------------------------------------------------
  finalize_nightly:
    needs: [prep, build]
    if: needs.prep.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      # 3c) Build and push Docker image with tag "nightly"
      - name: Checkout Repo for Docker build
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=nightly
            type=raw,value=${{ needs.prep.outputs.version_tag }}

      - name: Download Server x64 Artifacts
        uses: actions/download-artifact@v4
        with:
          name: LANCommander.Server-Linux-x64-v${{ needs.prep.outputs.version_tag }}.zip
          path: ./

      - name: Extract Server Artifacts
        run: |
          mkdir -p ./LANCommander.Server/published
          unzip ./LANCommander.Server-Linux-x64-v${{ needs.prep.outputs.version_tag }}.zip -d ./LANCommander.Server/published

      # - name: Download Server arm64 Artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: LANCommander.Server-Linux-arm64-v${{ needs.prep.outputs.version_tag }}.zip
      #     path: ./published

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./LANCommander.Server
          file: ./LANCommander.Server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:nightly
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ needs.prep.outputs.version_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ needs.prep.outputs.version_tag }}
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          provenance: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Save version to artifact
        run: echo "${{ needs.prep.outputs.version_tag }}" > version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version.${{ needs.prep.outputs.version_tag }}
          path: version.txt