name: LANCommander Nightly

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 3AM CST
    # CST is UTC-6, so midnight CST = 09:00 UTC
    - cron: '0 9 * * *'
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write

jobs:
  # --------------------------------------------------------------------------
  # 1) PREP JOB: figure out the latest semver, build nightly version,
  #    check if there are commits since the last nightly tag. If none,
  #    skip the rest of the workflow.
  # --------------------------------------------------------------------------
  prep:
    runs-on: [self-hosted, Linux Server]
    outputs:
      version_semver: ${{ steps.set_version.outputs.VERSION_SEMVER }}
      version_tag: ${{ steps.set_version.outputs.VERSION_TAG }}
      changed: ${{ steps.check_diff.outputs.changed }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Ensure we get all tags so we can find the latest
          fetch-depth: 0

      - name: Determine last semver and build nightly version
        id: set_version
        shell: bash
        run: |
          # Fetch all tags
          git fetch --tags

          # Grab the last semver-ish tag (e.g., "v1.2.3", "v1.2.3-debug", or "1.2.3-nightly")
          LAST_SEMVER_TAG="$(git tag --list --sort=-v:refname | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+' | head -n1)"

          if [ -z "$LAST_SEMVER_TAG" ]; then
            echo "No semver tag found; defaulting to 0.0.0"
            LAST_SEMVER_TAG="0.0.0"
          fi

          # Remove prefix 'v' and any suffix like "-debug", "-nightly", etc.
          CLEAN_TAG="$(echo "${LAST_SEMVER_TAG#v}" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')"

          # Build a nightly version string, e.g., "1.2.3-nightly.20250127"
          DATE=$(date +'%Y%m%d')
          FINAL_VERSION="${CLEAN_TAG}-nightly.${DATE}"

          echo "Last semver tag: $LAST_SEMVER_TAG"
          echo "Clean semver tag: $CLEAN_TAG"
          echo "Nightly version: $FINAL_VERSION"

          # Set output variables for GitHub Actions
          echo "VERSION_SEMVER=$CLEAN_TAG" >> $GITHUB_ENV
          echo "VERSION_TAG=$FINAL_VERSION" >> $GITHUB_ENV
          echo "::set-output name=VERSION_SEMVER::$CLEAN_TAG"
          echo "::set-output name=VERSION_TAG::$FINAL_VERSION"

      - name: Check if commits since last nightly tag
        id: check_diff
        shell: bash
        run: |
          # Fetch the last nightly tag
          LAST_NIGHTLY_TAG="$(git tag --list --sort=-v:refname | grep -E 'nightly\.20[0-9]+' | head -n1 || true)"

          if [ -z "$LAST_NIGHTLY_TAG" ]; then
            echo "No previous nightly tag found. Marking as changed."
            echo "::set-output name=changed::true"
            exit 0
          fi

          # Check for commits since that tag
          set +e  # Disable exit on error temporarily
          COMMITS=$(git log "${LAST_NIGHTLY_TAG}"..HEAD --oneline 2>/dev/null || true)
          set -e  # Re-enable exit on error

          if [ -z "$COMMITS" ]; then
            echo "No commits since last nightly tag: $LAST_NIGHTLY_TAG"
            echo "::set-output name=changed::false"
          else
            echo "Found commits since $LAST_NIGHTLY_TAG"
            echo "::set-output name=changed::true"
          fi

  # --------------------------------------------------------------------------
  # 2) BUILD JOBS (Server/Launcher) - only run if changes == 'true'
  #    Each calls your local workflow YAML with correct indentation
  # --------------------------------------------------------------------------
  build_server_linux_arm64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Server.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: linux-arm64
      build_arch: arm64
      build_platform: Linux

  build_server_linux_x64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Server.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: linux-x64
      build_arch: x64
      build_platform: Linux

  build_server_osx_arm64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Server.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: osx-arm64
      build_arch: arm64
      build_platform: macOS

  build_server_osx_x64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Server.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: osx-x64
      build_arch: x64
      build_platform: macOS

  build_server_win_arm64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Server.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: win-arm64
      build_arch: arm64
      build_platform: Windows

  build_server_win_x64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Server.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: win-x64
      build_arch: x64
      build_platform: Windows

  build_launcher_linux_arm64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Launcher.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: linux-arm64
      build_arch: arm64
      build_platform: Linux

  build_launcher_linux_x64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Launcher.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: linux-x64
      build_arch: x64
      build_platform: Linux

  build_launcher_osx_arm64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Launcher.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: osx-arm64
      build_arch: arm64
      build_platform: macOS

  build_launcher_osx_x64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Launcher.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: osx-x64
      build_arch: x64
      build_platform: macOS

  build_launcher_win_arm64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Launcher.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: win-arm64
      build_arch: arm64
      build_platform: Windows

  build_launcher_win_x64:
    needs: prep
    if: needs.prep.outputs.changed == 'true'
    uses: ./.github/workflows/LANCommander.Launcher.yml
    with:
      version_semver: ${{ needs.prep.outputs.version_semver }}
      version_tag: ${{ needs.prep.outputs.version_tag }}
      build_runtime: win-x64
      build_arch: x64
      build_platform: Windows

  # --------------------------------------------------------------------------
  # 3) FINALIZE: if changes == 'true', gather artifacts + push Docker:nightly
  # --------------------------------------------------------------------------
  finalize_nightly:
    needs: 
      - prep
      - build_server_linux_arm64
      - build_server_linux_x64
      - build_server_osx_arm64
      - build_server_osx_x64
      - build_server_win_arm64
      - build_server_win_x64
      - build_launcher_linux_arm64
      - build_launcher_linux_x64
      - build_launcher_osx_arm64
      - build_launcher_osx_x64
      - build_launcher_win_arm64
      - build_launcher_win_x64
    if: needs.prep.outputs.changed == 'true'
    runs-on: [self-hosted, Linux Server]
    steps:
      # 3c) Build and push Docker image with tag "nightly"
      - name: Checkout Repo for Docker build
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            lancommander/lancommander:nightly
            lancommander/lancommander:${{ needs.prep.outputs.version_semver }}
            lancommander/lancommander:${{ needs.prep.outputs.version_tag }}
          labels: |
            org.opencontainers.image.title=LANCommander
            org.opencontainers.image.description="LANCommander nightly build"
            org.opencontainers.image.version=${{ needs.prep.outputs.version_semver }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.created_at }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
