name: LANCommander Server Restore

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build_dotnet_version:
        description: 'Build .NET Version'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: frabert/replace-string-action@v2
      name: Swap Path Backslashes
      id: swap_path_backslashes
      with:
        string: '${{ github.workspace }}'
        pattern: '\\'
        replace-with: '/'
        flags: g

    # Checkout code
    - uses: actions/checkout@v3
      with:
        submodules: true

    # .NET Setup and Caching
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.build_dotnet_version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Node.js Setup and Caching
    - name: Setup Node.js
      uses: actions/setup-node@v3.8.1
      with:
        node-version: '20'

    # Parallel UI builds
    - name: Build UI Components
      run: |
        cd ./LANCommander.UI
        npm install
        npm run package

    - name: Cache UI build
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/LANCommander.UI/wwwroot
        key: ${{ runner.os }}-ui-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-ui-
      
    - name: Install Server Node Dependencies
      run: |
        cd ./LANCommander.Server
        npm install

    - name: Cache Server npm packages
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/LANCommander.Server/node_modules
        key: ${{ runner.os }}-server-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-server-npm-

    - name: Install Launcher Node Dependencies
      run: |
        cd ./LANCommander.Launcher
        npm install

    - name: Cache Launcher npm packages
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/LANCommander.Launcher/node_modules
        key: ${{ runner.os }}-launcher-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-launcher-npm-